// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(CompanyXDbContext))]
    [Migration("20230620181131_InitMigration")]
    partial class InitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Entities.CompanyProject", b =>
                {
                    b.Property<int>("CompanyProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyProjectID"));

                    b.Property<DateTime>("EstimatedEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EstimatedStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyProjectID");

                    b.ToTable("CompanyProjects");
                });

            modelBuilder.Entity("DAL.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<string>("DepartmentDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentID = 1,
                            DepartmentDescription = "Information Technology Department",
                            DepartmentName = "IT"
                        },
                        new
                        {
                            DepartmentID = 2,
                            DepartmentDescription = "Marketing Department",
                            DepartmentName = "Marketing"
                        },
                        new
                        {
                            DepartmentID = 3,
                            DepartmentDescription = "Sales Department",
                            DepartmentName = "Sales"
                        },
                        new
                        {
                            DepartmentID = 4,
                            DepartmentDescription = "Finance Department",
                            DepartmentName = "Finance"
                        },
                        new
                        {
                            DepartmentID = 5,
                            DepartmentDescription = "Human Resources Department",
                            DepartmentName = "HR"
                        });
                });

            modelBuilder.Entity("DAL.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            Address = "123 Main St, City",
                            DepartmentID = 1,
                            FullName = "John Smith",
                            Skills = "Java, Python, SQL",
                            Status = 0,
                            Telephone = "1234567890"
                        },
                        new
                        {
                            EmployeeID = 2,
                            Address = "456 Elm St, City",
                            DepartmentID = 1,
                            FullName = "Emily Johnson",
                            Skills = "C#, JavaScript, HTML",
                            Status = 1,
                            Telephone = "9876543210"
                        },
                        new
                        {
                            EmployeeID = 3,
                            Address = "789 Oak St, City",
                            DepartmentID = 1,
                            FullName = "Michael Brown",
                            Skills = "PHP, MySQL, Laravel",
                            Status = 0,
                            Telephone = "5555555555"
                        },
                        new
                        {
                            EmployeeID = 4,
                            Address = "321 Maple St, City",
                            DepartmentID = 2,
                            FullName = "Jessica Davis",
                            Skills = "Marketing Strategy, Social Media",
                            Status = 0,
                            Telephone = "1111111111"
                        },
                        new
                        {
                            EmployeeID = 5,
                            Address = "654 Pine St, City",
                            DepartmentID = 2,
                            FullName = "David Wilson",
                            Skills = "Market Research, Advertising",
                            Status = 0,
                            Telephone = "9999999999"
                        },
                        new
                        {
                            EmployeeID = 6,
                            Address = "987 Cedar St, City",
                            DepartmentID = 3,
                            FullName = "Jennifer Thompson",
                            Skills = "Salesforce, Customer Relationship Management",
                            Status = 0,
                            Telephone = "7777777777"
                        },
                        new
                        {
                            EmployeeID = 7,
                            Address = "111 Walnut St, City",
                            DepartmentID = 3,
                            FullName = "Christopher Martinez",
                            Skills = "Negotiation, Sales Strategies",
                            Status = 0,
                            Telephone = "2222222222"
                        },
                        new
                        {
                            EmployeeID = 8,
                            Address = "555 Cherry St, City",
                            DepartmentID = 4,
                            FullName = "Elizabeth Turner",
                            Skills = "Accounting, Financial Analysis",
                            Status = 0,
                            Telephone = "3333333333"
                        },
                        new
                        {
                            EmployeeID = 9,
                            Address = "777 Olive St, City",
                            DepartmentID = 4,
                            FullName = "Matthew Harris",
                            Skills = "Budgeting, Tax Planning",
                            Status = 1,
                            Telephone = "4444444444"
                        },
                        new
                        {
                            EmployeeID = 10,
                            Address = "333 Pine St, City",
                            DepartmentID = 5,
                            FullName = "Sophia Clark",
                            Skills = "Business Consulting, Project Management",
                            Status = 0,
                            Telephone = "6666666666"
                        });
                });

            modelBuilder.Entity("DAL.Entities.HRStaff", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropjectRole")
                        .HasColumnType("int");

                    b.HasKey("Email");

                    b.ToTable("HRStaffs");

                    b.HasData(
                        new
                        {
                            Email = "admin@example.com",
                            BirthDate = new DateTime(1985, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "John Doe",
                            Password = "admin@123",
                            PropjectRole = 0
                        },
                        new
                        {
                            Email = "pm1@example.com",
                            BirthDate = new DateTime(1990, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Jane Smith",
                            Password = "pm@456",
                            PropjectRole = 1
                        },
                        new
                        {
                            Email = "pm2@example.com",
                            BirthDate = new DateTime(1988, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Michael Johnson",
                            Password = "pm@789",
                            PropjectRole = 1
                        },
                        new
                        {
                            Email = "hr1@example.com",
                            BirthDate = new DateTime(1993, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "David Johnson",
                            Password = "hr@789",
                            PropjectRole = 2
                        },
                        new
                        {
                            Email = "hr2@example.com",
                            BirthDate = new DateTime(1992, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Sarah Williams",
                            Password = "hr@987",
                            PropjectRole = 2
                        });
                });

            modelBuilder.Entity("DAL.Entities.ParticipatingProject", b =>
                {
                    b.Property<int>("CompanyProjectID")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CompanyProjectID", "EmployeeID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("ParticipatingProjects");
                });

            modelBuilder.Entity("DAL.Entities.Employee", b =>
                {
                    b.HasOne("DAL.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("DAL.Entities.ParticipatingProject", b =>
                {
                    b.HasOne("DAL.Entities.CompanyProject", "CompanyProject")
                        .WithMany("ParticipatingProjects")
                        .HasForeignKey("CompanyProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.Employee", "Employee")
                        .WithMany("ParticipatingProjects")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyProject");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DAL.Entities.CompanyProject", b =>
                {
                    b.Navigation("ParticipatingProjects");
                });

            modelBuilder.Entity("DAL.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("DAL.Entities.Employee", b =>
                {
                    b.Navigation("ParticipatingProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
